name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  milliseconds:  # id of input
    description: 'number of milliseconds to wait'
    required: true
    default: '1000'
  myToken:
    required: true
    description: 'your github token'
outputs:
  time: # output will be available to future steps
    description: 'uselss output'
runs:
  using: 'node12'
  main: 'dist/index.js'
